apiVersion: v2
name: certmanager-webhook-rcodezero
version: 0.7.1
description: Cert Manager Webhook for rcodezero.
type: application
home: https://github.com/blankdots/certmanager-webhook-rcodezero
maintainers:
  - name: Michael Braunoeder
    email: mib@nic.at
    url: https://www.rcodezero.at
appVersion: v0.7.1
