apiVersion: v2
name: certmanager-webhook-rcodezero
version: 0.6.4
description: Cert Manager Webhook for rcodezero.
type: application
home: https://github.com/safespring-community/certmanager-webhook-rcodezero
maintainers:
  - name: Michael Braunoeder
    email: mib@nic.at
    url: https://www.rcodezero.at
  - name: safespring
    email: hello@safespring.com
    url: https://www.safespring.com/
appVersion: v0.6.4
