apiVersion: v2
name: certmanager-webhook-rcodezero
version: 0.4.2
description: Cert Manager Webhook for RcdoezERo.
type: application
home: https://github.com/blankdots/certmanager-webhook-rcodezero
maintainers:
  - name: Michael Braunoeder
    email: mib@nic.at
    url: https://www.rcodezero.at
appVersion: v0.4.0
